language: go
go: 
 - 1.2
 - 1.3
 - release
 - tip

script:
 - go get .
 - go get github.com/smartystreets/goconvey/convey
 - go get code.google.com/p/go.tools/cmd/cover
 - go get github.com/mattn/goveralls
 - go test -covermode=count -coverprofile=profile.cov
 - goveralls -coverprofile=profile.cov -service=travis-ci
